#ifndef _MODBUS_CONFIGS_H
#define _MODBUS_CONFIGS_H

/* config tcp */
#define TCP_IP "0.0.0.0"
#define TCP_PORT 1234

#define SLAVE_ID 10

#define BITS_ADDRESS 0
#define BITS_NB 0

#define INPUT_BITS_ADDRESS 0
#define INPUT_BITS_NB 0

#define REGISTERS_ADDRESS 1000
#define REGISTERS_NB_MAX 255

#define INPUT_REGISTERS_ADDRESS 1000
#define INPUT_REGISTERS_NB 255

#endif // _MODBUS_CONFIGS_H
